from typing import List, Dict, Any

def format_ass_timestamp(seconds: float) -> str:
    """
    Converts seconds float into ASS timestamp format: H:MM:SS.cc (centiseconds)
    """
    hrs = int(seconds // 3600)
    mins = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    centis = int(round((seconds - int(seconds)) * 100))
    if centis >= 100:
        centis = 99
    return f"{hrs:d}:{mins:02d}:{secs:02d}.{centis:02d}"

def export_to_ass(
    segments: List[Dict[str, Any]],
    highlight_words: bool = False,
    include_speakers: bool = False
) -> str:
    """
    Exports subtitle segments to Advanced SubStation Alpha (.ass) format with styling and karaoke tags.
    """
    header = """[Script Info]
; Script generated by AI Subtitle Studio
Title: Subtitles
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,52,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,40,40,45,1
Style: Highlight,Arial,54,&H0000FFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,3,2,2,40,40,45,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    dialogues = []

    for seg in segments:
        start_str = format_ass_timestamp(seg.get("start_time", 0.0))
        end_str = format_ass_timestamp(seg.get("end_time", 0.0))
        speaker = seg.get("speaker", "Speaker 1")
        words = seg.get("words", [])

        if highlight_words and words:
            # Generate Karaoke tags: {\k<duration_in_centiseconds>}word
            karaoke_text_parts = []
            for w in words:
                w_text = w.get("word", "")
                w_start = w.get("start", seg.get("start_time", 0.0))
                w_end = w.get("end", seg.get("end_time", 0.0))
                duration_cs = max(1, int(round((w_end - w_start) * 100)))
                karaoke_text_parts.append(f"{{\\k{duration_cs}}}{w_text}")
            formatted_text = " ".join(karaoke_text_parts)
        else:
            raw_text = seg.get("text", "").replace("\n", "\\N")
            formatted_text = f"[{speaker}] {raw_text}" if include_speakers and speaker else raw_text

        dialogues.append(
            f"Dialogue: 0,{start_str},{end_str},Default,{speaker},0,0,0,,{formatted_text}"
        )

    return header + "\n".join(dialogues) + "\n"
