import re
from typing import List, Dict, Any

class SubtitlePostProcessor:
    """
    Cleans up transcription artifacts, AI hallucination loops, and unwanted filler words.
    """

    # Common Vietnamese and English filler words
    VIETNAMESE_FILLERS = {
        "à", "ờ", "ừm", "ừ", "hả", "nè", "nha", "nhé", "thì", "mà", "là", "kiểu như", "kiểu"
    }
    ENGLISH_FILLERS = {
        "um", "uh", "er", "ah", "like", "you know", "i mean", "so", "actually", "basically"
    }

    @classmethod
    def remove_hallucination_loops(cls, text: str) -> str:
        """
        Removes repetitive token loops generated by Whisper during low audio / background noise.
        e.g. 'Cảm ơn các bạn đã theo dõi Cảm ơn các bạn đã theo dõi Cảm ơn các bạn đã theo dõi'
        """
        if not text:
            return ""

        words = text.split()
        if len(words) < 6:
            return text

        # Check for repeating n-grams (phrases of 2 to 8 words repeating >= 3 times)
        for n in range(2, 9):
            for i in range(len(words) - n * 3 + 1):
                phrase = words[i:i + n]
                phrase_str = " ".join(phrase).lower()
                next_phrase = " ".join(words[i + n:i + n * 2]).lower()
                next_next_phrase = " ".join(words[i + n * 2:i + n * 3]).lower()

                if phrase_str == next_phrase == next_next_phrase:
                    # Found loop, truncate repeated portion
                    cleaned_words = words[:i + n]
                    return " ".join(cleaned_words)

        return text

    @classmethod
    def clean_text(cls, text: str, remove_fillers: bool = False, language: str = "vi") -> str:
        """
        Standardizes capitalization, punctuation spacing, and removes unwanted characters.
        """
        if not text:
            return ""

        # Normalize whitespace
        cleaned = re.sub(r'\s+', ' ', text).strip()

        # Fix punctuation spacing: 'word , word' -> 'word, word'
        cleaned = re.sub(r'\s+([,.;:?!])', r'\1', cleaned)

        # Capitalize first letter of sentences
        cleaned = re.sub(r'(^|[.!?]\s+)([a-zđàáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵ])',
                         lambda m: m.group(1) + m.group(2).upper(), cleaned)

        # Remove filler words if enabled
        if remove_fillers:
            fillers = cls.VIETNAMESE_FILLERS if language == "vi" else cls.ENGLISH_FILLERS
            words = cleaned.split()
            filtered = [w for w in words if w.lower().strip(",.;:?!") not in fillers]
            if filtered:
                cleaned = " ".join(filtered)

        return cleaned

    @classmethod
    def process_segments(
        cls,
        segments: List[Dict[str, Any]],
        filter_hallucinations: bool = True,
        remove_fillers: bool = False,
        language: str = "vi"
    ) -> List[Dict[str, Any]]:
        """
        Applies all post-processing filters to a list of segments.
        """
        processed = []
        for seg in segments:
            text = seg.get("text", "")
            if filter_hallucinations:
                text = cls.remove_hallucination_loops(text)
            
            text = cls.clean_text(text, remove_fillers=remove_fillers, language=language)

            if text:
                seg_copy = dict(seg)
                seg_copy["text"] = text
                processed.append(seg_copy)

        return processed
